---
title: "Generate Climate Indices"
author: "Inigo Peng"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
    toc_depth: 3
    number_sections: false

---

```{r setup, include=FALSE}
library(httr)
library(readr)
library(dplyr)
```

## Download El Nino Data
```{r}
nino_url <- "https://psl.noaa.gov/data/correlation/nina34.anom.data"
workspace <- here::here("data-raw")
nino_file <- paste0(workspace,"/n34.txt")
download.file(nino_url, destfile = nino_file, mode = "wb")
```

## Read In Eino 3.4 Index (N34)
```{r}
nino_raw <- read_lines(nino_file)
#Remove header
n34 <- nino_raw[-1]
# Convert to dataframe
n34_df <- read.table(text = n34, header = FALSE, fill = TRUE)
colnames(n34_df) <- c("Year", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
n34_df_filtered <- n34_df|>
  filter(Year <= year(Sys.Date()))|>
  filter(Year > 1978)|>
  filter(row_number() <= n()-1)|>
  mutate(across(-Year, as.numeric))
clean_n34_df <- n34_df_filtered |> 
  pivot_longer(cols = -Year, names_to = "month", values_to = "N34")|>
  mutate(N34 = ifelse(N34 == -99.99, NA, N34))|>
  mutate(
    month = match(tolower(month), tolower(month.abb)), 
    month = sprintf("%02d", month),  # Ensure two-digit format
    index = paste(Year, month, sep = "-"),
    month = as.numeric(month),
    Year = as.numeric(Year))|>
  relocate(index, .before = Year)
    
```

Normalize N34, PDO
```{r}
normalize <- function(x, min_val, max_val) {
  norm_value <- (x - min_val) / (max_val - min_val)
  return(max(0, min(1, norm_value)))  # Ensure within [0,1] range
}

normalizing_values <- read_csv(here::here( "data/min_max_pdo_n34.csv"))
colnames(normalizing_values) <- tolower(colnames(normalizing_values))

full_n34_df <- clean_n34_df|>
  left_join(normalizing_values, by = "month")|>
  rowwise()|>
  mutate(normalized_CN34 = 1 - normalize(N34, minimum_of_n34, maximum_of_n34)) |>
  dplyr::select(index, Year, month, N34, normalized_CN34)
write.csv(full_n34_df, here::here("data/n34_index_data.csv"), row.names = FALSE)
```
